### ISSUE TITLE
Error in some lines

### ISSUE THREAD

**Issue by jslegers73** [remco-k/domoticz-goodwe-modbusudp-plugin#2]
Hi yesterday I got an email from GoodWe that they updated the firmware of my GW-4200D-NS to version 1.14.20. I have tried the plugin today again on my test domoticz but it still gives an issue. 

![image](https://user-images.githubusercontent.com/6212673/195900879-d83ec56e-5ecf-4ab5-b4fe-735bed02046f.png)

I'm using the WiFi module. 

How can I test to see if the unit is running in the UDP mode?

**Comment by remco-k** [comment]
Are you sure your inverter is  accessible from your Pi?
Please post a little more of the log file. It seems to me that there are morr errors regarding this issue.

**Comment by remco-k** [comment]
I think I found a possible problem that might have caused the `vgrid2` keyerror in your case. 
I (hope I) fixed this issue, please download this beta 0.0.3 version to test if it is working now:
https://github.com/remco-k/domoticz-goodwe-modbusudp-plugin/archive/refs/heads/issue-2-vgrid2-keyerror.zip

Please report your results back. If a problem persists, please set `Log level` from `Normal` to `Extra` in Domoticz Setup->Hardware and report as much as information back as possible.

**Comment by jslegers73** [comment]
Hi Remco,

I tested it and it works. Thank you very much for your great work.

John Slegers

**Comment by remco-k** [comment]
Thank you for your feedback.  Glad it works.
I just merged the fix to master (version beta 0.0.3) and removed the branch created for this issue, so the above download link won't work anymore. 

For anyone else that needs this fix: just download the master branch of this software as this issue is fixed in there.
